/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectogrupo2.Interfaz;

/**
 *
 * @author RouryR
 */
public class Admin_Pasajeros extends javax.swing.JPanel {

    /**
     * Creates new form Admin_Pasajeros
     */
    public Admin_Pasajeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar_Pasajeros = new javax.swing.JButton();
        Ver_Lista = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), " Agregar pasajeros según las necesidades y características", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        setPreferredSize(new java.awt.Dimension(456, 312));

        Agregar_Pasajeros.setBackground(new java.awt.Color(0, 51, 153));
        Agregar_Pasajeros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Agregar_Pasajeros.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_Pasajeros.setText("Agregar Pasajero");
        Agregar_Pasajeros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar_Pasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_PasajerosActionPerformed(evt);
            }
        });

        Ver_Lista.setBackground(new java.awt.Color(0, 51, 153));
        Ver_Lista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Ver_Lista.setForeground(new java.awt.Color(255, 255, 255));
        Ver_Lista.setText("Ver lista ");
        Ver_Lista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pasajero.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Agregar_Pasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ver_Lista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Agregar_Pasajeros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ver_Lista)
                        .addGap(60, 60, 60))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Agregar_PasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_PasajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Agregar_PasajerosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_Pasajeros;
    private javax.swing.JButton Ver_Lista;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
