/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectogrupo1.Interfaz;

import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author RouryR
 */
public class About extends javax.swing.JDialog {

    /**
     * Creates new form About
     */
    
    
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        About = new javax.swing.JEditorPane();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Información del Proyecto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(255, 102, 102))); // NOI18N

        jScrollPane2.setViewportView(About);

        Exit.setBackground(new java.awt.Color(204, 0, 51));
        Exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("Cerrar");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(Exit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        String contenido =
    "<html>"
    + "<style>"
    + "body {"
    + "  background-color: #2c3e50; /* Color de fondo */"
    + "  text-align: center; /* Centro del texto */"
    + "  font-family: Arial, sans-serif; /* Tipo de letra */"
    + "}"
    + "h1, h2, ul, li {"
    + "  color: #ffcc33;"
    + "  font-size: 18px; /* Tamaño de fuente */"
    + "}"
    + "</style>"
     + "<h1 style='color: #B52B2B;'>Equipo de Desarrollo</h1>"
    + "<ul>"
    + "<li>✨ Diego Ramirez Corrales ✨</li>"
   + "<li>  ✨Moises Fonseca Barboza✨</li>"
+ "<li>✨Diego Ramirez Corrales✨</li>"
+ "<li>✨Estefan Leon Cordero✨</li>"
+ "<li>✨Juan Diego Araya Calderon✨</li>"
    + "</ul>"
    + "<h1 style='color: #B52B2B;'>Tecnologías Utilizadas</h1>"
    + "<ul>"
    + "<li>JDialog: Para crear ventanas emergentes en la interfaz del usuario.</li>"
    + "<li>Librería Gradient: Para efectos visuales atractivos en la interfaz.</li>"
    + "<li>SWING: Para la creación de la interfaz gráfica.</li>"
    + "</ul>"
   + "<h1 style='color: #B52B2B;'>Tareas del Equipo</h1>"
    + "<ul>"
    + "<li>Diego Ramirez: Creación del diagrama de clases.</li>"
    + "<li>Diego Ramirez:: Implementación de componentes y librerías.</li>"
    + "<li>Diego Ramirez: Desarrollo de componentes y librerías.</li>"
    + "<li>Diego Ramirez: Creación del repositorio y gestión del proyecto.</li>"
    + "</ul>"
    + "<h1 style='color: #B52B2B;'>Documentación y Herramientas</h1>"
    + "<ul>"
    + "<li>Ini4j: Utilizada para cargar configuraciones desde archivos .ini.</li>"
    + "</ul>"
    + "<h1 style='color: #B52B2B;'>Funcionalidades de la Interfaz</h1>"
    + "<ul>"
    + "<li>Agregar Pasajeros: Permite agregar usuarios de forma individual o mediante carga masiva.</li>"
    + "<li>Ver Vagón y Estaciones: Muestra el estado actual del vagón y las estaciones, así como la disposición de los pasajeros.</li>"
    + "</ul>"
    + "</html>";

About.setContentType("text/html");
About.setText(contenido);
About.setCaretPosition(0);

    }//GEN-LAST:event_formWindowOpened

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
   
    this.setVisible(false);  // Oculta la ventana actual
  
    this.dispose(); 
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                About dialog = new About(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane About;
    private javax.swing.JButton Exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
