/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectogrupo1.Interfaz;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.Timer;
import org.ini4j.Ini;
import popups.Popups;


/**
 *
 * @author RouryR
 */
public class Carga_ini extends javax.swing.JDialog {

    private int tiempoRestante = 5; // Tiempo restante en segundos
    private Timer timer;

    /**
     * Creates new form info_config
     */
    public Carga_ini(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mostrarContenidoConfig();

        // Configura un temporizador para actualizar el botón "Aceptar" cada segundo
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tiempoRestante--; // Reduce el tiempo restante en un segundo
                Aceptar.setText(" (" + tiempoRestante + "s)"); // Actualiza el texto del botón
                if (tiempoRestante <= 0) {
                    // Cierra el JDialog cuando el tiempo restante llega a cero
                    dispose();
                    timer.stop(); // Detiene el temporizador
                }
            }
        });
        timer.start(); // Inicia el temporizador
    } // Inicia el temporizador

    private void mostrarContenidoConfig() {
        String mensaje = "Aplicando configuración....";
        Popups Config = new Popups();
        Config.espera(mensaje);
        try {
        Ini ini = new Ini(new File("src/proyectogrupo1/config.ini"));
            Menu.asientos_fila_discapacidad = Integer.parseInt(ini.get("Configuracion", "asientos_fila_discapacidad"));
           Menu.asientos_fila_sin_discapacidad1 = Integer.parseInt(ini.get("Configuracion", "asientos_fila_sin_discapacidad1"));
           Menu.asientos_fila_sin_discapacidad2 = Integer.parseInt(ini.get("Configuracion", "asientos_fila_sin_discapacidad2"));
           Menu.nombre_empresa = ini.get("Configuracion", "nombre_empresa");
           Menu.tiempo_avance_segundos = Integer.parseInt(ini.get("Configuracion", "tiempo_avance_segundos"));
            Menu.costo_por_kilometro = Integer.parseInt(ini.get("Configuracion", "costo_por_kilometro"));
    } catch (FileNotFoundException e) {
        String error_MSG = "Error: Archivo de configuracion no encontrado.";
        Popups error = new Popups();
        error.error(error_MSG);
        System.out.println("Error: Archivo de configuracion no encontrado.");
        //System.out.println("Ruta del archivo: " + new File("config.ini").getAbsolutePath());
    } catch (IOException e) {
        e.printStackTrace();
    }
        
        
        
        StringBuilder contenido = new StringBuilder();
        // Acceder a los valores de configuración
        int asientosFilaDiscapacidad = Menu.asientos_fila_discapacidad;
        int asientosFilaSinDiscapacidad1 = Menu.asientos_fila_sin_discapacidad1;
        int asientosFilaSinDiscapacidad2 = Menu.asientos_fila_sin_discapacidad2;
        String nombreEmpresa = Menu.nombre_empresa;
        
        int tiempoAvanceSegundos = Menu.tiempo_avance_segundos;
        double costoPorKilometro = Menu.costo_por_kilometro;

        // Ahora puedes usar estos valores en tu lógica del programa
        contenido.append("Filas de Vagon con Discapacidad: ").append(asientosFilaDiscapacidad).append("\n \n");
        contenido.append("Filas de Vagon sin Discapacidad 1: ").append(asientosFilaSinDiscapacidad1).append("\n \n");
        contenido.append("Filas de Vagon sin Discapacidad 2: ").append(asientosFilaSinDiscapacidad2).append("\n \n");
        contenido.append("Nombre de la Empresa: ").append(nombreEmpresa).append("\n \n");
        contenido.append("Tiempo de Avance entre Paradas (segundos): ").append(tiempoAvanceSegundos).append("\n \n");
        contenido.append("Costo por Kilometro Recorrido: ₡").append(costoPorKilometro).append(" colones");
        info.setText(contenido.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D) g;
                int w = getWidth();
                int h = getHeight();
                Color colorInicial = Color.decode("#D16BA5"); // Color inicial en formato HEX
                Color colorFinal = Color.decode("#86A8E7"); // Color final en formato HEX
                GradientPaint gradientPaint = new GradientPaint(0, 0, colorInicial, w, h, colorFinal);
                g2d.setPaint(gradientPaint);
                g2d.fillRect(0, 0, w, h);
            }
        };
        jScrollPane1 = new javax.swing.JScrollPane();
        info = new javax.swing.JTextArea();
        Aceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        info.setEditable(false);
        info.setColumns(20);
        info.setRows(5);
        info.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        info.setFocusable(false);
        jScrollPane1.setViewportView(info);

        Aceptar.setBackground(new java.awt.Color(51, 102, 255));
        Aceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(255, 255, 255));
        Aceptar.setText("Exit");
        Aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("Configuracion Aplicada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(Aceptar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Aceptar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        dispose();
                    timer.stop(); // Detiene el temporizador
    }//GEN-LAST:event_AceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carga_ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carga_ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carga_ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carga_ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Carga_ini dialog = new Carga_ini(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JTextArea info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
